# Data Preprocessing for Climate Data

In [20]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [21]:
%matplotlib inline

# Reading Dataset
### Dates which are present in the vegetable dataset those only consider for processing

In [22]:
climate = pd.read_csv('Climate_Rajasthan.csv')
vegetables = pd.read_csv('Jalore.csv')
climate.head()
#len(vegetables)

,Year,Month,Date,Temp_Max,Temp_Avg,Temp_Min,Dew_Max,Dew_Avg,Dew_Min,Humid_Max,Humid_Avg,Humid_Min,Wind_Max,Wind_Avg,Wind_Min,Pressure_Max,Pressure_Avg,Pressure_Min,Precipitation_Total
0,2019,Jan,1,75,61.1,48,45,40.9,34,76,50.5,22,6,2.5,0,28.8,28.7,28.6,0
1,2019,Jan,2,77,63.6,52,45,40.6,32,76,47.0,19,8,2.6,0,28.8,28.8,28.7,0
2,2019,Jan,3,75,62.5,50,48,36.9,23,82,44.4,14,7,2.6,0,28.9,28.8,28.8,0
3,2019,Jan,4,70,61.0,50,45,41.1,34,67,49.4,32,8,4.0,0,28.8,28.7,28.4,0
4,2019,Jan,5,61,56.6,54,46,42.4,41,67,58.8,52,8,7.5,7,28.8,28.7,28.7,0

# String is converted into Required Format

In [23]:
climate['Date Format'] = climate['Year'].map(str) + "-" + climate['Month'].astype(str) + "-" + climate['Date'].astype(str)
climate['Date Format'] = pd.to_datetime(climate['Date Format'])
climate.head()

,Year,Month,Date,Temp_Max,Temp_Avg,Temp_Min,Dew_Max,Dew_Avg,Dew_Min,Humid_Max,Humid_Avg,Humid_Min,Wind_Max,Wind_Avg,Wind_Min,Pressure_Max,Pressure_Avg,Pressure_Min,Precipitation_Total,Date Format
0,2019,Jan,1,75,61.1,48,45,40.9,34,76,50.5,22,6,2.5,0,28.8,28.7,28.6,0,2019-01-01
1,2019,Jan,2,77,63.6,52,45,40.6,32,76,47.0,19,8,2.6,0,28.8,28.8,28.7,0,2019-01-02
2,2019,Jan,3,75,62.5,50,48,36.9,23,82,44.4,14,7,2.6,0,28.9,28.8,28.8,0,2019-01-03
3,2019,Jan,4,70,61.0,50,45,41.1,34,67,49.4,32,8,4.0,0,28.8,28.7,28.4,0,2019-01-04
4,2019,Jan,5,61,56.6,54,46,42.4,41,67,58.8,52,8,7.5,7,28.8,28.7,28.7,0,2019-01-05

In [24]:
vegetables.head()
vegetables.shape
climate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 789 entries, 0 to 788
Data columns (total 20 columns):
Year                   789 non-null int64
Month                  789 non-null object
Date                   789 non-null int64
Temp_Max               789 non-null int64
Temp_Avg               789 non-null float64
Temp_Min               789 non-null int64
Dew_Max                789 non-null int64
Dew_Avg                789 non-null float64
Dew_Min                789 non-null int64
Humid_Max              789 non-null int64
Humid_Avg              789 non-null float64
Humid_Min              789 non-null int64
Wind_Max               789 non-null int64
Wind_Avg               789 non-null float64
Wind_Min               789 non-null int64
Pressure_Max           789 non-null float64
Pressure_Avg           789 non-null float64
Pressure_Min           789 non-null float64
Precipitation_Total    789 non-null int64
Date Format            789 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(7), int64(11), object(1)
memory usage: 120.3+ KB

In [25]:
vegetables = vegetables[vegetables['District Name'] == "Jalore"]
vegetables = vegetables[vegetables['Market Name'] == "Jalore"]
vegetables.head()

,Sl no.,District Name,Market Name,Commodity,Variety,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date
0,1,Jalore,Jalore,Garlic,Other,FAQ,14000,15000,14500,28-Dec-19
1,2,Jalore,Jalore,Garlic,Other,FAQ,140,150,145,21-Nov-19
2,3,Jalore,Jalore,Garlic,Other,FAQ,140,150,145,20-Nov-19
3,4,Jalore,Jalore,Garlic,Other,FAQ,140,150,145,19-Nov-19
4,5,Jalore,Jalore,Garlic,Other,FAQ,5500,6000,5750,08-Sep-19

# Function to generate dates

In [26]:
pd.date_range(end='1/1/2018', periods= 2)

DatetimeIndex(['2017-12-31', '2018-01-01'], dtype='datetime64[ns]', freq='D')

In [27]:
vegetables['Price Date'] = pd.to_datetime(vegetables['Price Date'])
vegetables = vegetables.iloc[::-1]
#vegetables.head(10)

# Logic for averaging all parameters

In [28]:
final = []
days_required = 270.0
for row1 in vegetables['Price Date']:
    Temp_Avg, Dew_Avg,Humid_Avg,Wind_Avg,Pressure_Avg, Precipitation_Total = 0.0,0.0,0.0,0.0,0.0,0.0
    Temp_Max, Temp_Min, Dew_Max, Dew_Min, Humid_Max, Humid_Min,Wind_Max, Wind_Min, Pressure_Max, Pressure_Min = 0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
    for row2 in pd.date_range(end=row1, periods= days_required):
        try:
            temp = climate[climate['Date Format'] == row2]
            
            Temp_Max += float(temp['Temp_Max'])
            Temp_Avg += float(temp['Temp_Avg'])
            Temp_Min += float(temp['Temp_Min'])
        
            Dew_Max += float(temp['Dew_Max'])
            Dew_Avg += float(temp['Dew_Avg'])
            Dew_Min += float(temp['Dew_Min'])
        
            Humid_Max += float(temp['Humid_Max'])
            Humid_Avg += float(temp['Humid_Avg'])
            Humid_Min += float(temp['Humid_Min'])
        
            Wind_Max += float(temp['Wind_Max'])
            Wind_Avg += float(temp['Wind_Avg'])
            Wind_Min += float(temp['Wind_Min'])
        
            Pressure_Avg += float(temp['Pressure_Avg'])
        
            Precipitation_Total += float(temp['Precipitation_Total'])
        except:
            continue
        
    final.append([row1,Temp_Max/days_required,Temp_Avg / days_required, Temp_Min / days_required,Dew_Min/ days_required,Dew_Avg/ days_required, Dew_Min/ days_required, Humid_Max/ days_required,Humid_Avg/ days_required, Humid_Min/ days_required, Wind_Max/ days_required, Wind_Avg/ days_required, Wind_Min/ days_required, Pressure_Max/ days_required, Pressure_Avg/ days_required, Pressure_Min/ days_required, Precipitation_Total/ days_required])

In [29]:
final

[[Timestamp('2019-01-02 00:00:00'),
  91.87037037037037,
  82.44740740740738,
  68.07777777777778,
  46.422222222222224,
  56.29222222222219,
  46.422222222222224,
  66.84444444444445,
  47.63000000000004,
  28.251851851851853,
  13.377777777777778,
  5.474814814814817,
  1.3555555555555556,
  0.0,
  28.243703703703705,
  0.0,
  0.0],
 [Timestamp('2019-01-14 00:00:00'),
  90.5962962962963,
  81.15333333333326,
  67.16296296296296,
  46.41851851851852,
  56.10814814814813,
  46.41851851851852,
  68.3037037037037,
  48.89037037037039,
  29.09259259259259,
  13.011111111111111,
  5.365925925925927,
  1.374074074074074,
  0.0,
  28.26222222222223,
  0.0,
  0.0],
 [Timestamp('2019-02-03 00:00:00'),
  88.71851851851852,
  79.13851851851844,
  64.88888888888889,
  46.27777777777778,
  55.98111111111108,
  46.27777777777778,
  71.43333333333334,
  51.115555555555595,
  30.177777777777777,
  12.52962962962963,
  5.0922222222222215,
  1.2037037037037037,
  0.0,
  28.401851851851895,
  0.0,
  0.0],
 [Timestamp('2019-02-06 00:00:00'),
  88.37407407407407,
  78.78259259259251,
  64.55185185185185,
  46.2962962962963,
  56.03148148148147,
  46.2962962962963,
  72.01851851851852,
  51.57111111111115,
  30.42962962962963,
  12.485185185185186,
  5.075185185185185,
  1.2,
  0.0,
  28.40407407407412,
  0.0,
  0.0],
 [Timestamp('2019-03-07 00:00:00'),
  84.96666666666667,
  75.50037037037038,
  61.67037037037037,
  45.44074074074074,
  55.1248148148148,
  45.44074074074074,
  75.15925925925926,
  53.75481481481488,
  31.52962962962963,
  11.566666666666666,
  4.946666666666662,
  1.174074074074074,
  0.0,
  28.44111111111115,
  0.0,
  0.0],
 [Timestamp('2019-03-08 00:00:00'),
  84.89259259259259,
  75.4325925925926,
  61.903703703703705,
  45.577777777777776,
  55.027407407407395,
  45.577777777777776,
  75.07037037037037,
  53.70888888888896,
  31.603703703703705,
  11.566666666666666,
  4.947037037037032,
  1.174074074074074,
  0.0,
  28.442962962963005,
  0.0,
  0.0],
 [Timestamp('2019-03-09 00:00:00'),
  84.8037037037037,
  75.34666666666668,
  61.818518518518516,
  45.49629629629629,
  54.93851851851851,
  45.49629629629629,
  75.04444444444445,
  53.693703703703775,
  31.6,
  11.555555555555555,
  4.926666666666662,
  1.162962962962963,
  0.0,
  28.444814814814855,
  0.0,
  0.0],
 [Timestamp('2019-03-12 00:00:00'),
  84.58148148148148,
  75.10703703703709,
  61.57037037037037,
  45.21851851851852,
  54.70074074074073,
  45.21851851851852,
  75.11851851851851,
  53.67148148148154,
  31.537037037037038,
  11.485185185185186,
  4.8477777777777735,
  1.0851851851851853,
  0.0,
  28.450000000000042,
  0.0,
  0.0],
 [Timestamp('2019-03-13 00:00:00'),
  84.4888888888889,
  75.01333333333338,
  61.477777777777774,
  45.15925925925926,
  54.63148148148147,
  45.15925925925926,
  75.12962962962963,
  53.69222222222229,
  31.55925925925926,
  10.91851851851852,
  4.815925925925923,
  1.0629629629629629,
  0.0,
  28.45148148148152,
  0.0,
  0.0],
 [Timestamp('2019-03-14 00:00:00'),
  84.41111111111111,
  74.92111111111116,
  61.37777777777778,
  45.092592592592595,
  54.56555555555555,
  45.092592592592595,
  75.16666666666667,
  53.71851851851858,
  31.57037037037037,
  10.903703703703703,
  4.802962962962961,
  1.0518518518518518,
  0.0,
  28.452962962963,
  0.0,
  0.0],
 [Timestamp('2019-03-15 00:00:00'),
  84.33333333333333,
  74.84555555555558,
  61.596296296296295,
  45.2037037037037,
  54.49518518518517,
  45.2037037037037,
  75.23333333333333,
  53.726296296296354,
  31.633333333333333,
  10.877777777777778,
  4.791851851851851,
  1.0444444444444445,
  0.0,
  28.45481481481485,
  0.0,
  0.0],
 [Timestamp('2019-03-16 00:00:00'),
  84.24814814814815,
  74.77481481481483,
  61.51111111111111,
  45.077777777777776,
  54.38851851851851,
  45.077777777777776,
  75.23703703703704,
  53.677777777777834,
  31.58888888888889,
  10.825925925925926,
  4.782592592592591,
  1.037037037037037,
  0.0,
  28.45629629629633,
  0.0,
  0.0],
 [Timestamp('2019-03-17 00:00:00'),
  84.17407407407407,
  74.70074074074077,
  61.44074074074074,
  44.977777777777774,
  54.30148148148148,
  44.977777777777774,
  75.17037037037036,
  53.65222222222227,
  31.566666666666666,
  10.792592592592593,
  4.77111111111111,
  1.037037037037037,
  0.0,
  28.45740740740744,
  0.0,
  0.0],
 [Timestamp('2019-03-19 00:00:00'),
  84.02222222222223,
  74.54518518518522,
  61.25555555555555,
  44.84814814814815,
  54.164814814814804,
  44.84814814814815,
  75.21481481481482,
  53.65518518518523,
  31.562962962962963,
  10.766666666666667,
  4.757777777777776,
  1.037037037037037,
  0.0,
  28.460000000000033,
  0.0,
  0.0],
 [Timestamp('2019-03-20 00:00:00'),
  83.95925925925926,
  74.48111111111115,
  61.166666666666664,
  44.74814814814815,
  54.07703703703703,
  44.74814814814815,
  75.25555555555556,
  53.62925925925931,
  31.537037037037038,
  10.762962962962963,
  4.748148148148148,
  1.025925925925926,
  0.0,
  28.46111111111114,
  0.0,
  0.0],
 [Timestamp('2019-03-24 00:00:00'),
  83.84814814814816,
  74.36703703703708,
  61.01111111111111,
  44.25185185185185,
  53.660370370370366,
  44.25185185185185,
  74.76666666666667,
  53.17037037037042,
  31.16296296296296,
  10.511111111111111,
  4.712222222222221,
  0.9851851851851852,
  0.0,
  28.471851851851874,
  0.0,
  0.0],
 [Timestamp('2019-03-26 00:00:00'),
  83.84444444444445,
  74.35000000000002,
  61.22962962962963,
  44.25925925925926,
  53.43481481481482,
  44.25925925925926,
  74.4888888888889,
  52.80703703703709,
  31.062962962962963,
  10.488888888888889,
  4.6933333333333325,
  0.9703703703703703,
  0.0,
  28.47481481481484,
  0.0,
  0.0],
 [Timestamp('2019-03-28 00:00:00'),
  83.85555555555555,
  74.31925925925928,
  61.15185185185185,
  44.12222222222222,
  53.20777777777778,
  44.12222222222222,
  74.13703703703703,
  52.5381481481482,
  30.914814814814815,
  10.748148148148148,
  4.663333333333331,
  0.9518518518518518,
  0.0,
  28.477037037037064,
  0.0,
  0.0],
 [Timestamp('2019-03-30 00:00:00'),
  83.88518518518518,
  74.31555555555559,
  61.10740740740741,
  43.837037037037035,
  53.00703703703704,
  43.837037037037035,
  73.89259259259259,
  52.309629629629676,
  30.696296296296296,
  10.725925925925926,
  4.63148148148148,
  0.9074074074074074,
  0.0,
  28.478888888888914,
  0.0,
  0.0],
 [Timestamp('2019-03-31 00:00:00'),
  83.88518518518518,
  74.31444444444449,
  61.1037037037037,
  43.662962962962965,
  52.86925925925926,
  43.662962962962965,
  73.78888888888889,
  52.163333333333384,
  30.57037037037037,
  10.733333333333333,
  4.629629629629629,
  0.8925925925925926,
  0.0,
  28.48000000000002,
  0.0,
  0.0],
 [Timestamp('2019-04-01 00:00:00'),
  83.88518518518518,
  74.29333333333336,
  61.05925925925926,
  43.50370370370371,
  52.73259259259259,
  43.50370370370371,
  73.63703703703703,
  52.0355555555556,
  30.45925925925926,
  10.718518518518518,
  4.6203703703703685,
  0.8888888888888888,
  0.0,
  28.481111111111133,
  0.0,
  0.0],
 [Timestamp('2019-04-02 00:00:00'),
  83.88148148148149,
  74.26814814814819,
  61.0,
  43.36666666666667,
  52.61518518518518,
  43.36666666666667,
  73.54814814814814,
  51.93296296296301,
  30.374074074074073,
  10.703703703703704,
  4.61037037037037,
  0.8814814814814815,
  0.0,
  28.482222222222244,
  0.0,
  0.0],
 [Timestamp('2019-04-03 00:00:00'),
  83.87407407407407,
  74.24888888888891,
  60.95185185185185,
  43.237037037037034,
  52.508518518518514,
  43.237037037037034,
  73.48518518518519,
  51.845925925925975,
  30.303703703703704,
  10.688888888888888,
  4.603333333333332,
  0.8814814814814815,
  0.0,
  28.483333333333352,
  0.0,
  0.0],
 [Timestamp('2019-04-04 00:00:00'),
  83.85925925925926,
  74.22333333333336,
  60.925925925925924,
  43.13703703703704,
  52.41481481481482,
  43.13703703703704,
  73.38518518518518,
  51.77962962962967,
  30.255555555555556,
  10.677777777777777,
  4.59111111111111,
  0.8777777777777778,
  0.0,
  28.484814814814836,
  0.0,
  0.0],
 [Timestamp('2019-04-06 00:00:00'),
  83.85925925925926,
  74.21259259259263,
  60.91111111111111,
  42.91111111111111,
  52.20037037037038,
  42.91111111111111,
  73.0925925925926,
  51.547407407407455,
  30.107407407407408,
  10.670370370370371,
  4.5848148148148145,
  0.8777777777777778,
  0.0,
  28.489629629629647,
  0.0,
  0.0],
 [Timestamp('2019-04-07 00:00:00'),
  83.89259259259259,
  74.23444444444446,
  60.9,
  42.785185185185185,
  52.08740740740742,
  42.785185185185185,
  72.94444444444444,
  51.362592592592634,
  29.94814814814815,
  11.514814814814814,
  4.605555555555554,
  0.8740740740740741,
  0.0,
  28.490370370370385,
  0.0,
  0.0],
 [Timestamp('2019-04-08 00:00:00'),
  83.91851851851852,
  74.25592592592595,
  60.9,
  42.68518518518518,
  52.00111111111112,
  42.68518518518518,
  72.77407407407408,
  51.17444444444448,
  29.807407407407407,
  11.162962962962963,
  4.590000000000001,
  0.8666666666666667,
  0.0,
  28.49148148148149,
  0.0,
  0.0],
 [Timestamp('2019-04-09 00:00:00'),
  83.97037037037038,
  74.28925925925928,
  60.907407407407405,
  42.544444444444444,
  51.900370370370375,
  42.544444444444444,
  72.61481481481482,
  50.95185185185189,
  29.58888888888889,
  11.174074074074074,
  4.591851851851852,
  0.8740740740740741,
  0.0,
  28.49222222222223,
  0.0,
  0.0],
 [Timestamp('2019-04-10 00:00:00'),
  84.0111111111111,
  74.32851851851852,
  60.907407407407405,
  42.41111111111111,
  51.793333333333344,
  42.41111111111111,
  72.42222222222222,
  50.72851851851855,
  29.42222222222222,
  11.151851851851852,
  4.594814814814815,
  0.8740740740740741,
  0.0,
  28.49333333333334,
  0.0,
  0.0],
 [Timestamp('2019-04-11 00:00:00'),
  84.07037037037037,
  74.37222222222223,
  60.925925925925924,
  42.31111111111111,
  51.671481481481486,
  42.31111111111111,
  72.18148148148148,
  50.48407407407411,
  29.274074074074075,
  11.155555555555555,
  4.606296296296296,
  0.8777777777777778,
  0.0,
  28.494444444444447,
  0.0,
  0.0],
 [Timestamp('2019-04-12 00:00:00'),
  84.11851851851851,
  74.40259259259261,
  60.92962962962963,
  42.17037037037037,
  51.55962962962964,
  42.17037037037037,
  71.97037037037038,
  50.26481481481485,
  29.07037037037037,
  11.148148148148149,
  4.6103703703703705,
  0.8851851851851852,
  0.0,
  28.49555555555556,
  0.0,
  0.0],
 [Timestamp('2019-04-13 00:00:00'),
  84.11851851851851,
  74.42629629629629,
  61.233333333333334,
  42.32962962962963,
  51.46777777777779,
  42.32962962962963,
  71.75925925925925,
  50.10000000000004,
  29.118518518518517,
  11.137037037037038,
  4.605925925925925,
  0.8851851851851852,
  0.0,
  28.497037037037035,
  0.0,
  0.0],
 [Timestamp('2019-04-14 00:00:00'),
  84.13703703703703,
  74.45370370370371,
  61.237037037037034,
  42.21111111111111,
  51.35851851851853,
  42.21111111111111,
  71.54814814814814,
  49.902222222222264,
  28.992592592592594,
  11.125925925925927,
  4.599259259259259,
  0.8814814814814815,
  0.0,
  28.498148148148147,
  0.0,
  0.0],
 [Timestamp('2019-04-16 00:00:00'),
  84.21111111111111,
  74.45740740740739,
  61.474074074074075,
  42.285185185185185,
  51.18740740740741,
  42.285185185185185,
  71.35185185185185,
  49.60851851851856,
  28.877777777777776,
  11.24074074074074,
  4.634074074074073,
  0.8888888888888888,
  0.0,
  28.502222222222215,
  0.0,
  0.0],
 [Timestamp('2019-04-18 00:00:00'),
  84.18518518518519,
  74.40814814814813,
  61.39259259259259,
  42.12592592592593,
  51.04703703703704,
  42.12592592592593,
  71.28518518518518,
  49.4055555555556,
  28.91111111111111,
  11.251851851851852,
  4.642592592592591,
  0.8814814814814815,
  0.0,
  28.504814814814807,
  0.0,
  0.0],
 [Timestamp('2019-04-23 00:00:00'),
  84.41851851851852,
  74.53777777777775,
  61.08888888888889,
  41.262962962962966,
  50.501111111111115,
  41.262962962962966,
  70.39259259259259,
  48.322962962963004,
  27.72222222222222,
  11.24074074074074,
  4.59148148148148,
  0.8148148148148148,
  0.0,
  28.504444444444434,
  0.0,
  0.0],
 [Timestamp('2019-04-24 00:00:00'),
  84.50740740740741,
  74.59370370370367,
  61.114814814814814,
  41.11851851851852,
  50.38333333333333,
  41.11851851851852,
  70.17037037037036,
  48.08074074074078,
  27.462962962962962,
  11.262962962962963,
  4.592222222222221,
  0.8037037037037037,
  0.0,
  28.505185185185173,
  0.0,
  0.0],
 [Timestamp('2019-05-05 00:00:00'),
  85.1,
  74.99999999999997,
  61.82592592592592,
  40.06666666666667,
  49.11370370370371,
  40.06666666666667,
  68.17777777777778,
  46.117037037037086,
  26.05185185185185,
  11.24074074074074,
  4.475925925925926,
  0.6481481481481481,
  0.0,
  28.510370370370346,
  0.0,
  0.0],
 [Timestamp('2019-05-07 00:00:00'),
  85.1962962962963,
  75.0633333333333,
  61.84074074074074,
  39.70740740740741,
  48.778888888888886,
  39.70740740740741,
  67.67407407407407,
  45.66444444444449,
  25.68148148148148,
  11.24074074074074,
  4.48074074074074,
  0.6296296296296297,
  0.0,
  28.511111111111084,
  0.0,
  0.0],
 [Timestamp('2019-05-09 00:00:00'),
  85.31481481481481,
  75.1485185185185,
  61.89259259259259,
  39.41851851851852,
  48.53888888888889,
  39.41851851851852,
  67.28148148148148,
  45.267407407407454,
  25.31111111111111,
  11.255555555555556,
  4.488148148148146,
  0.6222222222222222,
  0.0,
  28.512962962962934,
  0.0,
  0.0],
 [Timestamp('2019-05-12 00:00:00'),
  85.4037037037037,
  75.22555555555553,
  61.64074074074074,
  38.922222222222224,
  48.259629629629636,
  38.922222222222224,
  66.68888888888888,
  44.728888888888925,
  24.848148148148148,
  11.11111111111111,
  4.4940740740740726,
  0.6074074074074074,
  0.0,
  28.51259259259256,
  0.0,
  0.0],
 [Timestamp('2019-05-14 00:00:00'),
  85.47037037037038,
  75.26925925925924,
  61.8962962962963,
  38.99629629629629,
  48.092592592592595,
  38.99629629629629,
  66.52592592592593,
  44.39370370370374,
  24.748148148148147,
  11.11111111111111,
  4.492222222222221,
  0.6,
  0.0,
  28.513703703703673,
  0.0,
  0.0],
 [Timestamp('2019-05-26 00:00:00'),
  86.04074074074074,
  75.6818518518518,
  62.03333333333333,
  37.88148148148148,
  47.20703703703703,
  37.88148148148148,
  64.84814814814816,
  42.21444444444445,
  22.533333333333335,
  11.196296296296296,
  4.44037037037037,
  0.5222222222222223,
  0.0,
  28.52296296296292,
  0.0,
  0.0],
 [Timestamp('2019-05-29 00:00:00'),
  86.29629629629629,
  75.86074074074072,
  62.148148148148145,
  37.45185185185185,
  46.86,
  37.45185185185185,
  64.12222222222222,
  41.50629629629629,
  21.82962962962963,
  11.166666666666666,
  4.405555555555554,
  0.48148148148148145,
  0.0,
  28.52296296296292,
  0.0,
  0.0],
 [Timestamp('2019-05-30 00:00:00'),
  86.4074074074074,
  75.94740740740738,
  62.2,
  37.31481481481482,
  46.75222222222222,
  37.31481481481482,
  63.84814814814815,
  41.227407407407405,
  21.566666666666666,
  11.177777777777777,
  4.412592592592591,
  0.4888888888888889,
  0.0,
  28.52296296296292,
  0.0,
  0.0],
 [Timestamp('2019-05-31 00:00:00'),
  86.51481481481481,
  76.03037037037035,
  62.25555555555555,
  37.2037037037037,
  46.660000000000004,
  37.2037037037037,
  63.574074074074076,
  40.96074074074074,
  21.314814814814813,
  11.207407407407407,
  4.4174074074074055,
  0.48148148148148145,
  0.0,
  28.52296296296292,
  0.0,
  0.0],
 [Timestamp('2019-06-02 00:00:00'),
  86.7,
  76.18148148148144,
  62.36296296296296,
  37.03333333333333,
  46.47666666666667,
  37.03333333333333,
  63.15555555555556,
  40.52629629629629,
  20.974074074074075,
  11.222222222222221,
  4.4251851851851844,
  0.4703703703703704,
  0.0,
  28.522222222222183,
  0.0,
  0.0],
 [Timestamp('2019-06-13 00:00:00'),
  87.67407407407407,
  76.9981481481481,
  63.15185185185185,
  36.2962962962963,
  45.66481481481482,
  36.2962962962963,
  61.04074074074074,
  38.31518518518518,
  19.72962962962963,
  11.344444444444445,
  4.44148148148148,
  0.42592592592592593,
  0.0,
  28.519259259259226,
  0.0,
  0.0],
 [Timestamp('2019-06-18 00:00:00'),
  87.71111111111111,
  77.04740740740738,
  63.51851851851852,
  36.611111111111114,
  45.78037037037037,
  36.611111111111114,
  61.148148148148145,
  38.45851851851851,
  19.94814814814815,
  11.34074074074074,
  4.434074074074074,
  0.40370370370370373,
  0.0,
  28.517037037037003,
  0.0,
  0.0],
 [Timestamp('2019-06-26 00:00:00'),
  88.07037037037037,
  77.32629629629626,
  63.77037037037037,
  36.62592592592593,
  45.83925925925925,
  36.62592592592593,
  60.75925925925926,
  37.997777777777756,
  19.437037037037037,
  11.38888888888889,
  4.422592592592593,
  0.362962962962963,
  0.0,
  28.514814814814784,
  0.0,
  0.0],
 [Timestamp('2019-07-03 00:00:00'),
  88.27407407407408,
  77.54296296296295,
  64.54814814814814,
  37.32222222222222,
  46.1148148148148,
  37.32222222222222,
  60.81111111111111,
  38.11666666666664,
  19.72962962962963,
  11.496296296296297,
  4.5188888888888865,
  0.3925925925925926,
  0.0,
  28.508888888888855,
  0.0,
  0.0],
 [Timestamp('2019-07-06 00:00:00'),
  88.19259259259259,
  77.51999999999998,
  64.6037037037037,
  37.67037037037037,
  46.38629629629628,
  37.67037037037037,
  61.21851851851852,
  38.642592592592564,
  20.248148148148147,
  11.525925925925925,
  4.528888888888887,
  0.4,
  0.0,
  28.50481481481478,
  0.0,
  0.0],
 [Timestamp('2019-07-11 00:00:00'),
  88.22222222222223,
  77.61888888888888,
  64.47037037037038,
  37.91851851851852,
  46.81481481481482,
  37.91851851851852,
  61.7,
  39.197037037037,
  20.644444444444446,
  11.396296296296295,
  4.583703703703702,
  0.43703703703703706,
  0.0,
  28.49666666666664,
  0.0,
  0.0],
 [Timestamp('2019-07-12 00:00:00'),
  88.22962962962963,
  77.64518518518517,
  64.51481481481481,
  38.044444444444444,
  46.89925925925927,
  38.044444444444444,
  61.81111111111111,
  39.279999999999966,
  20.744444444444444,
  11.41851851851852,
  4.605925925925924,
  0.45555555555555555,
  0.0,
  28.499629629629602,
  0.0,
  0.0],
 [Timestamp('2019-07-17 00:00:00'),
  88.26666666666667,
  77.76666666666662,
  64.72962962962963,
  38.55185185185185,
  47.31703703703703,
  38.55185185185185,
  62.22962962962963,
  39.688148148148116,
  21.203703703703702,
  11.488888888888889,
  4.695555555555553,
  0.5148148148148148,
  0.0,
  28.493703703703662,
  0.0,
  0.0],
 [Timestamp('2019-07-19 00:00:00'),
  88.28888888888889,
  77.81370370370367,
  64.81851851851852,
  38.81481481481482,
  47.54777777777777,
  38.81481481481482,
  62.525925925925925,
  39.99888888888886,
  21.451851851851853,
  11.525925925925925,
  4.695925925925924,
  0.5148148148148148,
  0.0,
  28.491481481481443,
  0.0,
  0.0],
 [Timestamp('2019-08-09 00:00:00'),
  88.54074074074074,
  78.44407407407401,
  65.64444444444445,
  41.425925925925924,
  50.1337037037037,
  41.425925925925924,
  65.57407407407408,
  43.64518518518515,
  24.685185185185187,
  11.903703703703703,
  4.904074074074073,
  0.5703703703703704,
  0.0,
  28.457037037036994,
  0.0,
  0.0],
 [Timestamp('2019-08-10 00:00:00'),
  88.53333333333333,
  78.45555555555549,
  65.69259259259259,
  41.53703703703704,
  50.236296296296295,
  41.53703703703704,
  65.73703703703704,
  43.83481481481478,
  24.855555555555554,
  11.92962962962963,
  4.922962962962962,
  0.5777777777777777,
  0.0,
  28.455925925925886,
  0.0,
  0.0],
 [Timestamp('2019-08-11 00:00:00'),
  88.54814814814814,
  78.47962962962957,
  65.74074074074075,
  41.62222222222222,
  50.31777777777778,
  41.62222222222222,
  65.87037037037037,
  43.965925925925895,
  24.985185185185184,
  11.911111111111111,
  4.927777777777776,
  0.5851851851851851,
  0.0,
  28.454814814814778,
  0.0,
  0.0],
 [Timestamp('2019-08-12 00:00:00'),
  88.57037037037037,
  78.51851851851845,
  65.80740740740741,
  41.78148148148148,
  50.42333333333333,
  41.78148148148148,
  65.93703703703704,
  44.09259259259255,
  25.174074074074074,
  11.922222222222222,
  4.937777777777776,
  0.6037037037037037,
  0.0,
  28.453703703703667,
  0.0,
  0.0],
 [Timestamp('2019-08-13 00:00:00'),
  88.5925925925926,

In [30]:
len(final)

82

In [31]:
#final

In [32]:
df = pd.DataFrame(data = final, columns = ['Date','Temp_Max', 'Temp_Avg', 'Temp_Min', 'Dew_Max', 'Dew_Avg', 'Dew_Min', 'Humid_Max', 'Humid_Avg','Humid_Min','Wind_Max','Wind_Avg','Wind_Min','Pressure_Max', 'Pressure_Avg','Pressure_Min', 'Precipitation_Total'])

# CSV File is generated here

In [33]:
df.to_csv('climate_Jalore_270.csv')

In [ ]:
#for row2 in pd.date_range(end=row1, periods= days_required):
        #temp = climate[climate['Date Format'] == row2]
        #print(row2)
        '''Temp_Avg += int(temp['Temp_Avg'])
        Dew_Avg += int(temp['Dew_Avg'])
        Humid_Avg += int(temp['Humid_Avg'])
        Wind_Avg += int(temp['Wind_Avg']) 
        Pressure_Avg += int(temp['Pressure_Avg'])
        Precipitation_Total += int(temp['Precipitation_Total'])
    final.append([row1,Temp_Avg / month_required, Dew_Avg/month_required, Humid_Avg/month_required, Wind_Avg/month_required, Pressure_Avg/month_required,Precipitation_Total/month_required])'''
'''for row1 in vegetables['Price Date']:
    Temp_Avg, Dew_Avg,Humid_Avg,Wind_Avg,Pressure_Avg, Precipitation_Total = 0,0,0,0,0,0
    temp = climate[climate['Date Format'] == row1]
    print(temp)'''
'''
Temp_Max += temp['Temp_Max'].astype(float)
        Temp_Avg += temp['Temp_Avg'].astype(float)
        Temp_Min += temp['Temp_Min'].astype(float)
        
        Dew_Max += temp['Dew_Max'].astype(float)
        Dew_Avg += temp['Dew_Avg'].astype(float)
        Dew_Min += temp['Dew_Min'].astype(float)
        
        Humid_Max += temp['Humid_Max'].astype(float)
        Humid_Avg += temp['Humid_Avg'].astype(float)
        Humid_Min += temp['Humid_Min'].astype(float)
        
        Wind_Max += temp['Wind_Max'].astype(float)
        Wind_Avg += temp['Wind_Avg'].astype(float)
        Wind_Min += temp['Wind_Min'].astype(float)
        
        Pressure_Avg += temp['Pressure_Avg'].astype(float)
        
        Precipitation_Total += temp['Precipitation_Total'].astype(float)
    final.append([row1,Temp_Max/days_required,Temp_Avg / days_required, Temp_Min / days_required,Dew_Min/ days_required,Dew_Avg/ days_required, Dew_Min/ days_required, Humid_Max/ days_required,Humid_Avg/ days_required, Humid_Min/ days_required, Wind_Max/ days_required, Wind_Avg/ days_required, Wind_Min/ days_required, Pressure_Max/ days_required, Pressure_Avg/ days_required, Pressure_Min/ days_required, Precipitation_Total/ days_required])
    
Temp_Max += int(temp['Temp_Max'])
        Temp_Avg += int(temp['Temp_Avg'])
        Temp_Min += int(temp['Temp_Min'])
        
        Dew_Max += int(temp['Dew_Max'])
        Dew_Avg += int(temp['Dew_Avg'])
        Dew_Min += int(temp['Dew_Min'])
        
        Humid_Max += int(temp['Humid_Max'])
        Humid_Avg += int(temp['Humid_Avg'])
        Humid_Min += int(temp['Humid_Min'])
        
        Wind_Max += int(temp['Wind_Max'])
        Wind_Avg += int(temp['Wind_Avg'])
        Wind_Min += int(temp['Wind_Min'])
        
        Pressure_Avg += int(temp['Pressure_Avg'])
        
        Precipitation_Total += int(temp['Precipitation_Total'])
'''